# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c77962b9da62ce623c46b24b8c97f2b1"
name = "hpn-bundle-builder-discount"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
